---
- name: Deploy VM templates
  hosts: proxmox_hosts

  tasks:
    - name: Import variables from Ansible vault
      ansible.builtin.include_vars: secrets.yml
    
    - name: Deploy templates with proxmox_template_vm
      ansible.builtin.include_role:
        name: joshrnoll.homelab.proxmox_template_vm
      vars: 
        # Required to provide at least one
        proxmox_template_vm_distros:
          - fedora
          - ubuntu

        # Required proxmox credentials
        proxmox_template_vm_proxmox_username: "{{ proxmox_username }}" # From Ansible vault
        proxmox_template_vm_proxmox_api_token_id: "{{ proxmox_api_token_id }}" # From Ansible vault
        proxmox_template_vm_proxmox_api_token_secret: "{{ proxmox_api_token_secret }}" # From Ansible vault
        
        # Optional customizations for ubuntu
        proxmox_template_vm_ubuntu_storage: "zfs-pool-01"
        proxmox_template_vm_ubuntu_name: ubuntu-2204-template
        proxmox_template_vm_ubuntu_memory: 4096
        proxmox_template_vm_ubuntu_cores: 1
        proxmox_template_vm_ubuntu_ciuser: josh
        proxmox_template_vm_ubuntu_cipassword: "{{ cipassword }}" # From Ansible vault
        proxmox_template_vm_ubuntu_sshkeys: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}" # gets your ssh key from /home/user/.ssh/id_rsa.pub -- customize this to your needs
        proxmox_template_vm_ubuntu_vlan: 50

        # Optional customizations for fedora
        proxmox_template_vm_fedora_storage: "zfs-pool-01"        
        proxmox_template_vm_fedora_name: fedora-40-template
        proxmox_template_vm_fedora_memory: 4096
        proxmox_template_vm_fedora_cores: 1
        proxmox_template_vm_fedora_ciuser: josh
        proxmox_template_vm_fedora_cipassword: "{{ cipassword }}" # From Ansible vault
        proxmox_template_vm_fedora_sshkeys: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}" # gets your ssh key from /home/user/.ssh/id_rsa.pub -- customize this to your needs
        proxmox_template_vm_fedora_vlan: 50

        # Set to true if you have slow storage to avoid file locks
        proxmox_template_vm_slow_storage: true
...